apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appointment.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "appointment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    - host: appointment.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appointment.fullname" . }}
                port:
                  number: {{ .Values.service.port }}